let name = {
  '我':'wo',
  'wo':'我',
  'wodefuqin':'父亲',
  'fuqin':'父亲',
  'muqin':'母亲',
  'gege':'哥哥',
  'jiejie':'姐姐',
  'zhangfu':'老公',
  'qizi':'老婆',
  'didi':'弟弟',
  'meimei':'妹妹',
  'de':'的',
  'erzi':'儿子',
  'wodeerzi':'儿子',
  'wodeerzideerzi':'孙子',
  'wodeerzideerzideerzi':'曾孙',
  'wodeerzideerzideerzideerzi':'玄孙',
  'nver':'女儿',
  'wodenver':'女儿',
  'wodenverdenver':'外孙女',
  'wodenverdenverdenver':'外曾孙女',
  'fuqindenver':'女儿',
  'muqindenver':'女儿',
  'wodefuqin':'父亲',
  'wodefuqindefuqin':'爷爷',
  'wodefuqindefuqindefuqin':'太公',
  'wodefuqindefuqindefuqindefuqin':'高祖父',
  'wodefuqindefuqindefuqindefuqindefuqin':'天祖父',
  'wodemuqin':'母亲',
  'wodejiejie':'姐姐',
  'wodemeimei':'妹妹',
  'wodegege':'哥哥',
  'wodedidi':'弟弟',
  'fuqindefuqin':'爷爷',
  'fuqindefuqindefuqin':'太公',
  'fuqindefuqindefuqindefuqin':'高祖父',
  'fuqindefuqindefuqindefuqindefuqin':'天祖父',
  'muqindemuqin':'外婆',
  'muqindemuqindemuqin':'外太外婆',
  'gegedegege':'哥哥',
  'gegedegegedegege':'哥哥',
  'gegedegegedegegedegege':'哥哥',
  'gegedegegedegegedegegedegege':'哥哥',
  'gegedegegedegegedegegedegegedegege':'哥哥',
  'gegedegegedegegedegegedegegedegegedegege':'哥哥',
  'gegedegegedegegedegegedegegedegegedegegedegege':'哥哥',
  'jiejiedejiejie':'姐姐',
  'jiejiedejiejiedejiejie':'姐姐',
  'jiejiedejiejiedejiejiedejiejie':'姐姐',
  'jiejiedejiejiedejiejiedejiejiedejiejie':'姐姐',
  'jiejiedejiejiedejiejiedejiejiedejiejiedejiejie':'姐姐',
  'jiejiedejiejiedejiejiedejiejiedejiejiedejiejiedejiejie':'姐姐',
  'jiejiedejiejiedejiejiedejiejiedejiejiedejiejiedejiejiedejiejie':'姐姐',
  'dididedidi':'弟弟',
  'dididedididedidi':'弟弟',
  'dididedididedididedidi':'弟弟',
  'dididedididedididedididedidi':'弟弟',
  'dididedididedididedididedididedidi':'弟弟',
  'dididedididedididedididedididedididedidi':'弟弟',
  'dididedididedididedididedididedididedididedidi':'弟弟',
  'meimeidemeimei':'妹妹',
  'meimeidemeimeidemeimei':'妹妹',
  'meimeidemeimeidemeimeidemeimei':'妹妹',
  'meimeidemeimeidemeimeidemeimeidemeimei':'妹妹',
  'meimeidemeimeidemeimeidemeimeidemeimeidemeimei':'妹妹',
  'meimeidemeimeidemeimeidemeimeidemeimeidemeimeidemeimei':'妹妹',
  'meimeidemeimeidemeimeidemeimeidemeimeidemeimeidemeimeidemeimei':'妹妹',
  'wodegegedegege':'哥哥',
  'wodegegedegegedegege':'哥哥',
  'wodegegedegegedegegedegege':'哥哥',
  'wodegegedegegedegegedegegedegege':'哥哥',
  'wodegegedegegedegegedegegedegegedegege':'哥哥',
  'wodegegedegegedegegedegegedegegedegegedegege':'哥哥',
  'wodegegedegegedegegedegegedegegedegegedegegedegege':'哥哥',
  'wodejiejiedejiejie':'姐姐',
  'wodejiejiedejiejiedejiejie':'姐姐',
  'wodejiejiedejiejiedejiejiedejiejie':'姐姐',
  'wodejiejiedejiejiedejiejiedejiejiedejiejie':'姐姐',
  'wodejiejiedejiejiedejiejiedejiejiedejiejiedejiejie':'姐姐',
  'wodejiejiedejiejiedejiejiedejiejiedejiejiedejiejiedejiejie':'姐姐',
  'wodejiejiedejiejiedejiejiedejiejiedejiejiedejiejiedejiejiedejiejie':'姐姐',
  'wodedididedidi':'弟弟',
  'wodedididedididedidi':'弟弟',
  'wodedididedididedididedidi':'弟弟',
  'wodedididedididedididedididedidi':'弟弟',
  'wodedididedididedididedididedididedidi':'弟弟',
  'wodedididedididedididedididedididedididedidi':'弟弟',
  'wodedididedididedididedididedididedididedididedidi':'弟弟',
  'wodemeimeidemeimei':'妹妹',
  'wodemeimeidemeimeidemeimei':'妹妹',
  'wodemeimeidemeimeidemeimeidemeimei':'妹妹',
  'wodemeimeidemeimeidemeimeidemeimeidemeimei':'妹妹',
  'wodemeimeidemeimeidemeimeidemeimeidemeimeidemeimei':'妹妹',
  'wodemeimeidemeimeidemeimeidemeimeidemeimeidemeimeidemeimei':'妹妹',
  'wodemeimeidemeimeidemeimeidemeimeidemeimeidemeimeidemeimeidemeimei':'妹妹',
  'muqindejiejiedemeimei':'姨',
  'jiejiedezhangfudemeimei':'姻妹',
  'fuqindemuqin':'奶奶/嫲嫲',
  'fuqindemuqindemuqin':'外太婆',
  'wodefuqindemuqindedidi':'舅公',
  'wofuqindemuqindemeimei':'姨婆',
  'wofuqindemuqindeerzi':'叔父',
  'wofuqindemuqindenver':'姑姐',
  'meimeidejiejiedejiejiedenver':'外甥女',
  'muqindejiejiededididegege':'舅父',
  'muqindedididemeimeidejiejiedegege':'舅父',
  'fuqindeerzideqizi':'弟媳',
  'fuqindegegdedididenverdemeimei':'堂妹',
  'wodefuqindemuqin':'奶奶/嫲嫲',
  'wodefuqindegege':'伯父',
  'wodefuqindejiejie':'姑妈',
  'wodefuqindeqizi':'母亲',
  'wodefuqindedidi':'叔父',
  'wodefuqindemeimei':'姑姐',
  'wodefuqindeerzi':'比我年小的是弟弟，年长的是哥哥',
  'wodefuqindenver':'比我年小的是妹妹，年长的是姐姐',
  'wodemuqindefuqin':'外公',
  'wodemuqindemuqin':'外婆',
  'wodemuqindemuqindemuqin':'外太外婆',
  'wodemuqindegege':'舅父',
  'wodemuqindejiejie':'姨妈',
  'wodemuqindezhangfu':'父亲',
  'wodemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindedidi':'舅父',
  'wodemuqindemeimei':'姨',
  'wodemuqindeerzi':'比我年小的是弟弟，年长的是哥哥',
  'wodemuqindenver':'比我年小的是妹妹，年长的是姐姐',
  'wodegege':'哥哥',
  'wodegegedefuqin':'父亲',
  'wodegegedemuqin':'母亲',
  'wodegegedegege':'哥哥',
  'wodegegedejiejie':'姐姐',
  'wodegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedeqizi':'嫂子',
  'wodegegededidi':'比我年小的是弟弟，年长的是哥哥',
  'wodegegedemeimei':'比我年小的是妹妹，年长的是姐姐',
  'wodegegedeerzi':'侄子',
  'wodegegedenver':'侄女',
  'wodejiejie':'姐姐',
  'wodejiejiedefuqin':'父亲',
  'wodejiejiedemuqin':'母亲',
  'wodejiejiedegege':'哥哥',
  'wodejiejiedejiejie':'姐姐',
  'wodejiejiedezhangfu':'姐夫',
  'wodejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiededidi':'比我年小的是弟弟，年长的是哥哥',
  'wodejiejiedemeimei':'比我年小的是妹妹，年长的是姐姐',
  'wodejiejiedeerzi':'外甥',
  'wodejiejiedenver':'外甥女',
  'wodezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodezhangfudefuqin':'父亲',
  'wodezhangfudemuqin':'母亲',
  'wodezhangfudegege':'大伯',
  'wodezhangfudejiejie':'姑奶',
  'wodezhangfudeqizi':'自己',
  'wodezhangfudezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodezhangfudedidi':'叔仔',
  'wodezhangfudemeimei':'姑仔',
  'wodezhangfudeerzi':'儿子',
  'wodezhangfudenver':'女儿',
  'wodeqizidefuqin':'岳父',
  'wodeqizidemuqin':'岳母',
  'wodeqizidegege':'大舅',
  'wodeqizidejiejie':'大姨',
  'wodeqizidezhangfu':'自己',
  'wodeqizideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodeqizidedidi':'舅仔',
  'wodeqizidemeimei':'姨仔',
  'wodeqizideerzi':'儿子',
  'wodeqizidenver':'女儿',
  'wodedidi':'弟弟',
  'wodedididefuqin':'父亲',
  'wodedididemuqin':'母亲',
  'wodedididegege':'比我年小的是弟弟，年长的是哥哥',
  'wodedididejiejie':'比我年小的是妹妹，年长的是姐姐',
  'wodedidideqizi':'弟媳',
  'wodedididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididedidi':'弟弟',
  'wodedididemeimei':'妹妹',
  'wodedidideerzi':'侄子',
  'wodedididenver':'侄女',
  'wodemeimei':'妹妹',
  'wodemeimeidefuqin':'父亲',
  'wodemeimeidemuqin':'母亲',
  'wodemeimeidegege':'比我年小的是弟弟，年长的是哥哥',
  'wodemeimeidejiejie':'比我年小的是妹妹，年长的是姐姐',
  'wodemeimeidezhangfu':'妹夫',
  'wodemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidedidi':'弟弟',
  'wodemeimeidemeimei':'妹妹',
  'wodemeimeideerzi':'外甥',
  'wodemeimeidenver':'外甥女',
  'wodeerzi':'儿子',
  'wodeerzidefuqin':'男方是自己，女方是丈夫',
  'wodeerzidemuqin':'男方是老婆，女方是自己',
  'wodeerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodeerzidegege':'儿子',
  'wodeerzidejiejie':'女儿',
  'wodeerzideqizi':'儿媳妇',
  'wodeerzidedidi':'儿子',
  'wodeerzidemeimei':'女儿',
  'wodeerzideerzi':'孙子',
  'wodeerzidenver':'孙女',
  'wodenver':'女儿',
  'wodenverdefuqin':'我',
  'wodenverdemuqin':'老婆',
  'wodenverdegege':'儿子',
  'wodenverdejiejie':'女儿',
  'wodenverdezhangfu':'女婿',
  'wodenverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'wodenverdedidi':'儿子',
  'wodenverdemeimei':'儿女',
  'wodenverdeerzi':'外孙',
  'wodenverdenver':'外孙女',
  'fuqindefuqin':'爷爷',
  'fuqindefuqindefuqin':'太公',
  'fuqindefuqindemuqin':'太婆',
  'fuqindefuqindegege':'伯公',
  'fuqindefuqindejiejie':'姑婆',
  'fuqindefuqindeqizi':'奶奶/嫲嫲',
  'fuqindefuqindedidi':'叔公',
  'fuqindefuqindemeimei':'姑婆',
  'fuqindefuqindeerzi':'比父亲年小的是叔父，年长的是伯父',
  'fuqindefuqindenver':'比父亲年小的是姑姐，年长的是姑妈',
  'fuqindemuqin':'奶奶/嫲嫲',
  'fuqindemuqindefuqin':'外太公',
  'fuqindemuqindemuqin':'外太婆',
  'fuqindemuqindegege':'舅公',
  'fuqindemuqindejiejie':'姨婆',
  'fuqindemuqindezhangfu':'爷爷',
  'fuqindemuqindedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindemuqindedidi':'舅公',
  'fuqindemuqindemeimei':'姨婆',
  'fuqindemuqindeerzi':'年小的是叔父，年长的是伯父',
  'fuqindemuqindenver':'年小的是姑姐，年长的是姑妈',
  'fuqindegege':'伯父',
  'fuqindegegedefuqin':'父亲',
  'fuqindegegedemuqin':'母亲',
  'fuqindegegedegege':'伯父',
  'fuqindegegedejiejie':'姑妈',
  'fuqindegegedeqizi':'伯娘',
  'fuqindegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindegegededidi':'比父亲年小的是叔父，年长的是伯父',
  'fuqindegegedemeimei':'比父亲年小的是姑姐，年长的是姑妈',
  'fuqindegegedeerzi':'比我年长是堂兄，年小的是堂弟',
  'fuqindegegedenver':'比我年长是堂姐，年小的是堂妹',
  'fuqindejiejie':'姑妈',
  'fuqindejiejiedefuqin':'父亲',
  'fuqindejiejiedemuqin':'奶奶/嫲嫲',
  'fuqindejiejiedegege':'伯父',
  'fuqindejiejiedejiejie':'姑妈',
  'fuqindejiejiedezhangfu':'姑丈',
  'fuqindejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindejiejiededidi':'比父亲年小的是叔父，年长的是伯父',
  'fuqindejiejiedemeimei':'比父亲年小的是姑姐，年长的是姑妈',
  'fuqindejiejiedeerzi':'比我年长【姑】表兄，年小【姑】表弟',
  'fuqindejiejiedenver':'比我年长【姑】表姐，年小【姑】表妹',
  'fuqindeqizi':'母亲',
  'fuqindeqizidefuqin':'外公',
  'fuqindeqizidemuqin':'外婆',
  'fuqindeqizidegege':'舅父',
  'fuqindeqizidejiejie':'姨妈',
  'fuqindeqizidezhangfu':'父亲',
  'fuqindeqizideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindeqizidedidi':'舅父',
  'fuqindeqizidemeimei':'姨',
  'fuqindeqizideerzi':'比我年长是的哥哥，年小的是弟弟',
  'fuqindeqizidenver':'比我年长的是姐姐，年小的是妹妹',
  'fuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudefuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudemuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudegege':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudejiejie':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudedidi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudemeimei':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudeerzi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindezhangfudenver':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindedidi':'叔父',
  'fuqindedididefuqin':'爷爷',
  'fuqindedididemuqin':'奶奶/嫲嫲',
  'fuqindedididegege':'比父亲年小的是叔父，年长的是伯父',
  'fuqindedididejiejie':'比父亲年小的是姑姐，年长的是姑妈',
  'fuqindedidideqizi':'嬸',
  'fuqindedididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindedididedidi':'叔父',
  'fuqindedididemeimei':'姑姐',
  'fuqindedidideerzi':'比我年长是堂兄，年小的是堂弟',
  'fuqindedididenver':'比我年长是堂姐，年小的是堂妹',
  'fuqindemeimei':'姑姐',
  'fuqindemeimeidefuqin':'爷爷',
  'fuqindemeimeidemuqin':'奶奶/嫲嫲',
  'fuqindemeimeidegege':'比父亲年小的是叔父，年长的是伯父',
  'fuqindemeimeidejiejie':'比父亲年小的是姑姐，年长的是姑妈',
  'fuqindemeimeidezhangfu':'姑丈',
  'fuqindemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindemeimeidedidi':'叔父',
  'fuqindemeimeidemeimei':'姑姐',
  'fuqindemeimeideerzi':'我年长【姑】表兄，年小【姑】表弟',
  'fuqindemeimeidenver':'比我年长【姑】表姐，年小【姑】表妹',
  'fuqindeerzi':'比我年小的是弟弟，年长的是哥哥',
  'fuqindeerzidefuqin':'父亲',
  'fuqindeerzidemuqin':'母亲',
  'fuqindeerzidegege':'比我年长是的哥哥，年小的是弟弟',
  'fuqindeerzidejiejie':'比我年长的是姐姐，年小的是妹妹',
  'fuqindeerzideqizi':'比我年长是嫂子，比我年小的是弟媳',
  'fuqindeerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindeerzidedidi':'比我年长的哥哥，年小的是弟弟',
  'fuqindeerzidemeimei':'比我年长的是姐姐，年小的是妹妹',
  'fuqindeerzideerzi':'侄子',
  'fuqindeerzidenver':'侄女',
  'fuqindenver':'比我年长的是姐姐，年小的是妹妹',
  'fuqindenverdefuqin':'父亲',
  'fuqindenverdemuqin':'母亲',
  'fuqindenverdegege':'比我年长的是哥哥，年小的是弟弟',
  'fuqindenverdejiejie':'比我年长的是姐姐，年小的是妹妹',
  'fuqindenverdezhangfu':'比我年长的姐夫，年小的是妹夫',
  'fuqindenverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'fuqindenverdedidi':'比我年长的是哥哥，年小的是弟弟',
  'fuqindenverdemeimei':'比我年长的是姐姐，年小的是妹妹',
  'fuqindenverdeerzi':'姨甥',
  'fuqindenverdenver':'姨甥女',
  'muqindefuqin':'外公',
  'muqindefuqindefuqin':'外太公',
  'muqindefuqindemuqin':'外太婆',
  'muqindefuqindegege':'外太伯',
  'muqindefuqindejiejie':'外姑婆',
  'muqindefuqindeqizi':'外婆',
  'muqindefuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'muqindefuqindedidi':'外叔公',
  'muqindefuqindemeimei':'外姑婆',
  'muqindefuqindeerzi':'舅父',
  'muqindefuqindenver':'年长的是姨妈，年小的是姨',
  'muqindemuqin':'外婆',
  'muqindemuqindefuqin':'外太外公',
  'muqindemuqindemuqin':'外太外婆',
  'muqindemuqindegege':'外舅公',
  'muqindemuqindejiejie':'外姨婆',
  'muqindemuqindezhangfu':'外公',
  'muqindemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'muqindemuqindedidi':'外舅公',
  'muqindemuqindemeimei':'外舅婆',
  'muqindemuqindeerzi':'舅父',
  'muqindemuqindenver':'年长的是姨妈，年小的是姨',
  'muqindegege':'舅父',
  'muqindegegedefuqin':'外公',
  'muqindegegedemuqin':'外婆',
  'muqindegegedegege':'舅父',
  'muqindegegedejiejie':'年长的是姨妈，年小的是姨',
  'muqindegegedeqizi':'舅母',
  'muqindegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'muqindegegededidi':'舅父',
  'muqindegegedemeimei':'年长的是姨妈，年小的是姨',
  'muqindegegedeerzi':'比我年长【舅】表兄，年小的是【舅】表弟',
  'muqindegegedenver':'比我年长【舅】表姐，年小的是【舅】表妹',
  'muqindejiejie':'姨妈',
  'muqindejiejiedefuqin':'外公',
  'muqindejiejiedemuqin':'外婆',
  'muqindejiejiedegege':'舅父',
  'muqindejiejiedejiejie':'姨妈',
  'muqindejiejiedezhangfu':'姨丈',
  'muqindejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'muqindejiejiededidi':'舅父',
  'muqindejiejiedemeimei':'年长的是姨妈，年小的是姨',
  'muqindejiejiedeerzi':'比我年长【姨】表兄，年小的是【姨】表弟',
  'muqindejiejiedenver':'比我年长【姨】表姐，年小的是【姨】表妹',
  'muqindezhangfu':'父亲',
  'muqindezhangfudefuqin':'爷爷',
  'muqindezhangfudemuqin':'奶奶/嫲嫲',
  'muqindezhangfudegege':'伯父',
  'muqindezhangfudejiejie':'姑妈',
  'muqindezhangfudeqizi':'母亲',
  'muqindezhangfudezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'muqindezhangfudedidi':'叔父',
  'muqindezhangfudemeimei':'姑姐',
  'muqindezhangfudeerzi':'比我年长的是哥哥，年小的是弟弟',
  'muqindezhangfudenver':'比我年长的是姐姐，年小的是妹妹',
  'muqindedidi':'舅父',
  'muqindedididefuqin':'外公',
  'muqindedididemuqin':'奶奶/嫲嫲',
  'muqindedididegege':'舅父',
  'muqindedididejiejie':'年长的是姨妈，年小的是姨',
  'muqindedidideqizi':'舅母',
  'muqindedididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'muqindedididedidi':'舅父',
  'muqindedididemeimei':'年长的是姨妈，年小的是姨',
  'muqindedidideerzi':'比我年长【舅】表兄，年小的是【舅】表弟',
  'muqindedididenver':'比我年长【舅】表姐，年小的是【舅】表妹',
  'muqindemeimei':'姨',
  'muqindemeimeidefuqin':'外公',
  'muqindemeimeidemuqin':'外婆',
  'muqindemeimeidegege':'舅父',
  'muqindemeimeidejiejie':'年长的是姨妈，年小的是姨',
  'muqindemeimeidezhangfu':'姨丈',
  'muqindemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'muqindemeimeidedidi':'舅父',
  'muqindemeimeidemeimei':'姨',
  'muqindemeimeideerzi':'比我年长【姨】表兄，年小的是【姨】表弟',
  'muqindemeimeidenver':'比我年长【姨】表姐，年小的是【姨】表妹',
  'muqindeerzi':'比我年长是的哥哥，年小的是弟弟',
  'muqindeerzidefuqin':'父亲',
  'muqindeerzidemuqin':'母亲',
  'muqindeerzidegege':'比我年长是的哥哥，年小的是弟弟',
  'muqindeerzidejiejie':'比我年长的是姐姐，年小的是妹妹',
  'muqindeerzideqizi':'比我年长是嫂子，比我年小的是弟媳',
  'muqindeerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'muqindeerzidedidi':'比我年长是的哥哥，年小的是弟弟',
  'muqindeerzidemeimei':'比我年长的是姐姐，年小的是妹妹',
  'muqindeerzideerzi':'侄子',
  'muqindeerzidenver':'侄女',
  'muqindenver':'比我年长的是姐姐，年小的是妹妹',
  'muqindenverdefuqin':'父亲',
  'muqindenverdemuqin':'母亲',
  'muqindenverdegege':'比我年长是的哥哥，年小的是弟弟',
  'muqindenverdejiejie':'比我年长的是姐姐，年小的是妹妹',
  'muqindenverdezhangfu':'比我年长的姐夫，年小的是妹夫',
  'muqindenverdeqizi':'比我年长的姐夫，年小的是妹夫',
  'muqindenverdedidi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'muqindenverdemeimei':'比我年长的是姐姐，年小的是妹妹',
  'muqindenverdeerzi':'姨甥',
  'muqindenverdenver':'姨甥女',
  'gegedefuqin':'父亲',
  'gegedefuqindefuqin':'爷爷',
  'gegedefuqindemuqin':'奶奶/嫲嫲',
  'gegedefuqindegege':'伯父',
  'gegedefuqindejiejie':'姑妈',
  'gegedefuqindeqizi':'母亲',
  'gegedefuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'gegedefuqindedidi':'叔父',
  'gegedefuqindemeimei':'姑姐',
  'gegedefuqindeerzi':'比我年长是的哥哥，年小的是弟弟',
  'gegedefuqindenver':'比我年长的是姐姐，年小的是妹妹',
  'gegedemuqin':'母亲',
  'gegedemuqindefuqin':'外公',
  'gegedemuqindemuqin':'外婆',
  'gegedemuqindegege':'舅父',
  'gegedemuqindejiejie':'姨妈',
  'gegedemuqindezhangfu':'父亲',
  'gegedemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'gegedemuqindedidi':'舅父',
  'gegedemuqindemeimei':'姨',
  'gegedemuqindeerzi':'比我年长是的哥哥，年小的是弟弟',
  'gegedemuqindenver':'比我年长的是姐姐，年小的是妹妹',
  'gegedegege':'哥哥',
  'gegedegegedefuqin':'父亲',
  'gegedegegedemuqin':'母亲',
  'gegedegegedegege':'哥哥',
  'gegedegegedejiejie':'姐姐',
  'gegedegegedeqizi':'嫂',
  'gegedegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'gegedegegededidi':'比我年长是的哥哥，年小的是弟弟',
  'gegedegegedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'gegedegegedeerzi':'侄子',
  'gegedegegedenver':'侄女',
  'gegedejiejie':'姐姐',
  'gegedejiejiedefuqin':'父亲',
  'gegedejiejiedemuqin':'母亲',
  'gegedejiejiedegege':'哥哥',
  'gegedejiejiedejiejie':'姐姐',
  'gegedejiejiedezhangfu':'姐夫',
  'gegedejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'gegedejiejiededidi':'比我年长是的哥哥，年小的是弟弟',
  'gegedejiejiedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'gegedejiejiedeerzi':'姨甥',
  'gegedejiejiedenver':'姨甥女',
  'gegedeqizi':'嫂',
  'gegedeqizidefuqin':'姻世伯',
  'gegedeqizidemuqin':'姻伯母',
  'gegedeqizidegege':'比我年长是姻兄，年小的是姻弟',
  'gegedeqizidejiejie':'比我年长是姻姐，年小的是姻妹',
  'gegedeqizidezhangfu':'哥哥',
  'gegedeqizideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'gegedeqizidedidi':'我年长是姻兄，年小的是姻弟',
  'gegedeqizidemeimei':'比我年长是姻姐，年小的是姻妹',
  'gegedeqizideerzi':'侄子',
  'gegedeqizidenver':'侄女',
  'gegededidi':'比我年长的是哥哥，年小的是弟弟',
  'gegededididefuqin':'父亲',
  'gegededididemuqin':'母亲',
  'gegededididegege':'比我年长的哥哥，年小的是弟弟',
  'gegededididejiejie':'比我',
  'gegededididezhangfu':'比我年长的是姐姐，年小的是妹妹',
  'gegededidideqizi':'比我年长是嫂子，比我年小的是弟媳',
  'gegededididedidi':'比我年长是的哥哥，年小的是弟弟',
  'gegededididemeimei':'比我年长的是姐姐，年小的是妹妹',
  'gegededidideerzi':'侄子',
  'gegededididenver':'侄女',
  'gegedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'gegedemeimeidefuqin':'父亲',
  'gegedemeimeidemuqin':'母亲',
  'gegedemeimeidegege':'比我年长的哥哥，年小的是弟弟',
  'gegedemeimeidejiejie':'比我年长的是姐姐，年小的是妹妹',
  'gegedemeimeidezhangfu':'比我年长的是姐夫，年小的是妹夫',
  'gegedemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'gegedemeimeidedidi':'比我年长的是哥哥，年小的是弟弟',
  'gegedemeimeidemeimei':'比我年长的是姐姐，年小的是妹妹',
  'gegedemeimeideerzi':'侄子',
  'gegedemeimeidenver':'侄女',
  'gegedeerzi':'侄子',
  'gegedeerzidefuqin':'比我年长是的哥哥，年小的是弟弟',
  'gegedeerzidemuqin':'比我年长的是姐姐，年小的是妹妹',
  'gegedeerzidegege':'侄子',
  'gegedeerzidejiejie':'侄女',
  'gegedeerzideqizi':'侄媳妇',
  'gegedeerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'gegedeerzidedidi':'侄子',
  'gegedeerzidemeimei':'侄女',
  'gegedeerzideerzi':'侄孙',
  'gegedeerzidenver':'侄孙女',
  'gegedenver':'侄女',
  'gegedenverdefuqin':'比我年长是的哥哥，年小的是弟弟',
  'gegedenverdemuqin':'比我年长的是姐姐，年小的是妹妹',
  'gegedenverdegege':'侄子',
  'gegedenverdejiejie':'侄女',
  'gegedenverdezhangfu':'侄女婿',
  'gegedenverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'gegedenverdedidi':'侄子',
  'gegedenverdemeimei':'侄女',
  'gegedenverdeerzi':'外侄孙',
  'gegedenverdenver':'外侄孙女',
  'jiejiedefuqin':'父亲',
  'jiejiedefuqindefuqin':'爷爷',
  'jiejiedefuqindemuqin':'奶奶/嫲嫲',
  'jiejiedefuqindegege':'伯父',
  'jiejiedefuqindejiejie':'姑妈',
  'jiejiedefuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'jiejiedefuqindeqizi':'母亲',
  'jiejiedefuqindedidi':'叔父',
  'jiejiedefuqindemeimei':'姑姐',
  'jiejiedefuqindeerzi':'比我年长的是哥哥，年小的是弟弟',
  'jiejiedefuqindenver':'比我年长的是姐姐，年小的是妹妹',
  'jiejiedemuqin':'母亲',
  'jiejiedemuqindefuqin':'外公',
  'jiejiedemuqindemuqin':'外婆',
  'jiejiedemuqindegege':'舅父',
  'jiejiedemuqindejiejie':'姨妈',
  'jiejiedemuqindezhangfu':'父亲',
  'jiejiedemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'jiejiedemuqindedidi':'舅父',
  'jiejiedemuqindemeimei':'姨',
  'jiejiedemuqindeerzi':'比我年长是的哥哥，年小的是弟弟',
  'jiejiedemuqindenver':'比我年长的是姐姐，年小的是妹妹',
  'jiejiedegege':'哥哥',
  'jiejiedegegedefuqin':'父亲',
  'jiejiedegegedemuqin':'母亲',
  'jiejiedegegedegege':'哥哥',
  'jiejiedegegedejiejie':'姐姐',
  'jiejiedegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'jiejiedegegedeqizi':'嫂',
  'jiejiedegegededidi':'比我年长的是哥哥，年小的是弟弟',
  'jiejiedegegedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'jiejiedegegedeerzi':'侄子',
  'jiejiedegegedenver':'侄女',
  'jiejiedejiejie':'姐姐',
  'jiejiedejiejiedefuqin':'父亲',
  'jiejiedejiejiedemuqin':'母亲',
  'jiejiedejiejiedegege':'哥哥',
  'jiejiedejiejiedejiejie':'姐姐',
  'jiejiedejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'jiejiedejiejiedezhangfu':'姐夫',
  'jiejiedejiejiededidi':'比我年长的是哥哥，年小的是弟弟',
  'jiejiedejiejiedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'jiejiedejiejiedeerzi':'姨甥',
  'jiejiedejiejiedenver':'姨甥女',
  'jiejiedezhangfu':'姐夫',
  'jiejiedezhangfudefuqin':'姻世伯',
  'jiejiedezhangfudemuqin':'姻伯母',
  'jiejiedezhangfudegege':'比我年长是姻兄，年小的是姻弟',
  'jiejiedezhangfudejiejie':'比我年长是姻姐，年小的是姻妹',
  'jiejiedezhangfudeqizi':'姐姐',
  'jiejiedezhangfudezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'jiejiedezhangfudedidi':'比我年长是姻兄，年小的是姻弟',
  'jiejiedezhangfudemeimei':'比我年长是姻姐，年小的是姻妹',
  'jiejiedezhangfudeerzi':'姨甥',
  'jiejiedezhangfudenver':'姨甥女',
  'jiejiededidi':'比我年长是的哥哥，年小的是弟弟',
  'jiejiededididefuqin':'父亲',
  'jiejiededididemuqin':'母亲',
  'jiejiededididegege':'比我年长是的哥哥，年小的是弟弟',
  'jiejiededididejiejie':'比我年长的是姐姐，年小的是妹妹',
  'jiejiededididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'jiejiededidideqizi':'比我年长是嫂子，比我年小的是弟媳',
  'jiejiededididedidi':'比我年长是的哥哥，年小的是弟弟',
  'jiejiededididemeimei':'比我年长的是姐姐，年小的是妹妹',
  'jiejiededidideerzi':'侄子',
  'jiejiededididenver':'侄女',
  'jiejiedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'jiejiedemeimeidefuqin':'父亲',
  'jiejiedemeimeidemuqin':'母亲',
  'jiejiedemeimeidegege':'比我年长的哥哥，年小的是弟弟',
  'jiejiedemeimeidejiejie':'比我年长的是姐姐，年小的是妹妹',
  'jiejiedemeimeidezhangfu':'比我年长的姐夫，年小的是妹夫',
  'jiejiedemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'jiejiedemeimeidedidi':'比我年长的哥哥，年小的是弟弟',
  'jiejiedemeimeidemeimei':'比我年长的是姐姐，年小的是妹妹',
  'jiejiedemeimeideerzi':'姨甥',
  'jiejiedemeimeidenver':'姨甥女',
  'jiejiedeerzi':'姨甥',
  'jiejiedeerzidefuqin':'姐姐',
  'jiejiedeerzidemuqin':'姐夫',
  'jiejiedeerzidegege':'姨甥',
  'jiejiedeerzidejiejie':'姨甥女',
  'jiejiedeerzideqizi':'姨甥媳妇',
  'jiejiedeerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'jiejiedeerzidedidi':'姨甥',
  'jiejiedeerzidemeimei':'姨甥女',
  'jiejiedeerzideerzi':'姨甥孙',
  'jiejiedeerzidenver':'姨甥孙女',
  'jiejiedenver':'姨甥女',
  'jiejiedenverdefuqin':'姐夫',
  'jiejiedenverdemuqin':'姐姐',
  'jiejiedenverdegege':'姨甥',
  'jiejiedenverdejiejie':'姨甥女',
  'jiejiedenverdezhangfu':'姨甥女婿',
  'jiejiedenverdezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'jiejiedenverdedidi':'姨甥',
  'jiejiedenverdemeimei':'姨甥女',
  'jiejiedenverdeerzi':'姨甥孙',
  'jiejiedenverdenver':'姨甥孙女',
  'zhangfudefuqin':'父亲',
  'zhangfudefuqindefuqin':'爷爷',
  'zhangfudefuqindemuqin':'奶奶/嫲嫲',
  'zhangfudefuqindegege':'伯爷爷',
  'zhangfudefuqindejiejie':'姑奶奶',
  'zhangfudefuqindeqizi':'奶奶/嫲嫲',
  'zhangfudefuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'zhangfudefuqindedidi':'叔爷爷',
  'zhangfudefuqindemeimei':'姑奶奶',
  'zhangfudefuqindeerzi':'比丈夫年长的是大伯，年小的是叔仔',
  'zhangfudefuqindenver':'比丈夫年长的是姑奶，年小的是姑仔',
  'zhangfudemuqin':'奶奶/嫲嫲',
  'zhangfudemuqindefuqin':'爷爷',
  'zhangfudemuqindemuqin':'奶奶/嫲嫲',
  'zhangfudemuqindegege':'大伯',
  'zhangfudemuqindejiejie':'姨妈',
  'zhangfudemuqindezhangfu':'公公',
  'zhangfudemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'zhangfudemuqindedidi':'小叔',
  'zhangfudemuqindemeimei':'小姑',
  'zhangfudemuqindeerzi':'比丈夫年长的是大伯，年小的是叔仔',
  'zhangfudemuqindenver':'比丈夫年长的是姑奶，年小的是姑仔',
  'zhangfudegege':'大伯',
  'zhangfudegegedefuqin':'公公',
  'zhangfudegegedemuqin':'婆婆',
  'zhangfudegegedegege':'大伯',
  'zhangfudegegedejiejie':'姑奶',
  'zhangfudegegedeqizi':'大嫂',
  'zhangfudegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'zhangfudegegededidi':'比丈夫年长的是大伯，年小的是叔仔',
  'zhangfudegegedemeimei':'比丈夫年长的是姑奶，年小的是姑仔',
  'zhangfudegegedeerzi':'侄子',
  'zhangfudegegedenver':'侄女',
  'zhangfudejiejie':'姑奶',
  'zhangfudejiejiedefuqin':'公公',
  'zhangfudejiejiedemuqin':'婆婆',
  'zhangfudejiejiedegege':'大伯',
  'zhangfudejiejiedejiejie':'姑奶',
  'zhangfudejiejiedezhangfu':'姑爷',
  'zhangfudejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'zhangfudejiejiededidi':'比丈夫年长的是大伯，年小的是叔仔',
  'zhangfudejiejiedemeimei':'比丈夫年长的是姑奶，年小的是姑仔',
  'zhangfudejiejiedeerzi':'外甥',
  'zhangfudejiejiedenver':'外甥女',
  'zhangfudeqizi':'妻子',
  'zhangfudeqizidefuqin':'公公',
  'zhangfudeqizidemuqin':'婆婆',
  'zhangfudeqizidegege':'大舅子',
  'zhangfudeqizidejiejie':'大姨姐',
  'zhangfudeqizidezhangfu':'丈夫',
  'zhangfudeqizideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'zhangfudeqizidedidi':'小舅子',
  'zhangfudeqizidemeimei':'小姨子',
  'zhangfudeqizideerzi':'儿子',
  'zhangfudeqizidenver':'女儿',
  'zhangfudedidi':'小叔子',
  'zhangfudedididefuqin':'公公',
  'zhangfudedididemuqin':'婆婆',
  'zhangfudedididegege':'小叔子',
  'zhangfudedididejiejie':'比丈夫年长是大姑，年小时小姑',
  'zhangfudedidideqizi':'小婶',
  'zhangfudedididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'zhangfudedididedidi':'小叔',
  'zhangfudedididemeimei':'小姑',
  'zhangfudedidideerzi':'侄子',
  'zhangfudedididenver':'侄女',
  'zhangfudemeimei':'小姑',
  'zhangfudemeimeidefuqin':'公公',
  'zhangfudemeimeidemuqin':'婆婆',
  'zhangfudemeimeidegege':'比丈夫年长的是大伯，年小的是叔仔',
  'zhangfudemeimeidejiejie':'大姑姐',
  'zhangfudemeimeidezhangfu':'妹夫',
  'zhangfudemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'zhangfudemeimeidedidi':'叔仔',
  'zhangfudemeimeidemeimei':'姑仔',
  'zhangfudemeimeideerzi':'外甥',
  'zhangfudemeimeidenver':'外甥女',
  'zhangfudeerzi':'儿子',
  'zhangfudeerzidefuqin':'丈夫',
  'zhangfudeerzidemuqin':'自己',
  'zhangfudeerzidegege':'儿子',
  'zhangfudeerzidejiejie':'女儿',
  'zhangfudeerzidezhangfu':'丈夫',
  'zhangfudeerzideqizi':'儿媳妇',
  'zhangfudeerzidedidi':'小儿子',
  'zhangfudeerzidemeimei':'小女儿',
  'zhangfudeerzideerzi':'孙子',
  'zhangfudeerzidenver':'孙女',
  'zhangfudenver':'女儿',
  'zhangfudenverdefuqin':'丈夫',
  'zhangfudenverdemuqin':'自己',
  'zhangfudenverdegege':'儿子',
  'zhangfudenverdejiejie':'大女儿',
  'zhangfudenverdezhangfu':'女婿',
  'zhangfudenverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'zhangfudenverdedidi':'儿子',
  'zhangfudenverdemeimei':'小女儿',
  'zhangfudenverdeerzi':'孙子',
  'zhangfudenverdenver':'孙女',
  'qizidefuqin':'岳父',
  'qizidefuqindefuqin':'太岳父',
  'qizidefuqindemuqin':'太岳母',
  'qizidefuqindegege':'伯岳父',
  'qizidefuqindejiejie':'姑岳母',
  'qizidefuqindeqizi':'岳母',
  'qizidefuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'qizidefuqindedidi':'叔岳父',
  'qizidefuqindemeimei':'姑岳母',
  'qizidefuqindeerzi':'比妻子年长的是大舅，年轻的是舅仔',
  'qizidefuqindenver':'比妻子年长的是大姨，年轻的是姨仔',
  'qizidemuqin':'岳母',
  'qizidemuqindefuqin':'外太岳父',
  'qizidemuqindemuqin':'外太岳母',
  'qizidemuqindegege':'舅岳父',
  'qizidemuqindejiejie':'姨岳母',
  'qizidemuqindezhangfu':'岳父',
  'qizidemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'qizidemuqindedidi':'舅岳父',
  'qizidemuqindemeimei':'姨岳母',
  'qizidemuqindeerzi':'比妻子年长的是大舅，年轻的是舅仔',
  'qizidemuqindenver':'比妻子年长的是大姨，年轻的是姨仔',
  'qizidegege':'大舅',
  'qizidegegedefuqin':'岳父',
  'qizidegegedemuqin':'岳母',
  'qizidegegedegege':'大舅',
  'qizidegegedejiejie':'大姨',
  'qizidegegedeqizi':'舅嫂',
  'qizidegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'qizidegegededidi':'比妻子年长的是大舅，年轻的是舅仔',
  'qizidegegedemeimei':'比妻子年长的是大姨，年轻的是姨仔',
  'qizidegegedeerzi':'侄子',
  'qizidegegedenver':'侄女',
  'qizidejiejie':'大姨',
  'qizidejiejiedefuqin':'岳父',
  'qizidejiejiedemuqin':'岳母',
  'qizidejiejiedegege':'大舅',
  'qizidejiejiedejiejie':'大姨',
  'qizidejiejiedezhangfu':'襟兄',
  'qizidejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'qizidejiejiededidi':'比妻子年长的是大舅，年轻的是舅仔',
  'qizidejiejiedemeimei':'比妻子年长的是大姨，年轻的是姨仔',
  'qizidejiejiedeerzi':'姨甥',
  'qizidejiejiedenver':'姨甥女',
  'qizidezhangfu':'丈夫',
  'qizidezhangfudefuqin':'岳父',
  'qizidezhangfudemuqin':'岳母',
  'qizidezhangfudegege':'哥哥',
  'qizidezhangfudejiejie':'姐姐',
  'qizidezhangfudeqizi':'自己',
  'qizidezhangfudezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'qizidezhangfudedidi':'弟弟',
  'qizidezhangfudemeimei':'妹妹',
  'qizidezhangfudeerzi':'儿子',
  'qizidezhangfudenver':'女儿',
  'qizidedidi':'舅仔',
  'qizidedididefuqin':'岳父',
  'qizidedididemuqin':'岳母',
  'qizidedididegege':'比妻子年长的是大舅，年轻的是舅仔',
  'qizidedididejiejie':'比妻子年长的是大姨，年轻的是姨仔',
  'qizidedidideqizi':'舅弟媳',
  'qizidedididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'qizidedididedidi':'舅仔',
  'qizidedididemeimei':'姨仔',
  'qizidedidideerzi':'侄子',
  'qizidedididenver':'侄女',
  'qizidemeimei':'姨仔',
  'qizidemeimeidefuqin':'岳父',
  'qizidemeimeidemuqin':'岳母',
  'qizidemeimeidegege':'比妻子年长的是大舅，年轻的是舅仔',
  'qizidemeimeidejiejie':'比妻子年长的是大姨，年轻的是姨仔',
  'qizidemeimeidezhangfu':'襟弟',
  'qizidemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'qizidemeimeidedidi':'舅仔',
  'qizidemeimeidemeimei':'姨仔',
  'qizidemeimeideerzi':'姨甥',
  'qizidemeimeidenver':'姨甥女',
  'qizideerzi':'儿子',
  'qizideerzidefuqin':'自己',
  'qizideerzidemuqin':'妻子',
  'qizideerzidegege':'儿子',
  'qizideerzidejiejie':'女儿',
  'qizideerzideqizi':'儿媳妇',
  'qizideerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'qizideerzidedidi':'儿子',
  'qizideerzidemeimei':'女儿',
  'qizideerzideerzi':'孙子',
  'qizideerzidenver':'孙女',
  'qizidenver':'女儿',
  'qizidenverdefuqin':'自己',
  'qizidenverdemuqin':'妻子',
  'qizidenverdegege':'儿子',
  'qizidenverdejiejie':'女儿',
  'qizidenverdezhangfu':'女婿',
  'qizidenverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'qizidenverdedidi':'儿子',
  'qizidenverdemeimei':'女儿',
  'qizidenverdeerzi':'外孙',
  'qizidenverdenver':'外孙女',
  'dididefuqin':'父亲',
  'dididefuqindefuqin':'爷爷',
  'dididefuqindemuqin':'奶奶/嫲嫲',
  'dididefuqindegege':'伯父',
  'dididefuqindejiejie':'姑妈',
  'dididefuqindeqizi':'母亲',
  'dididefuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididefuqindedidi':'叔父',
  'dididefuqindemeimei':'姑姐',
  'dididefuqindeerzi':'比我年长是的哥哥，年小的是弟弟',
  'dididefuqindenver':'比我年长的是姐姐，年小的是妹妹',
  'dididemuqin':'母亲',
  'dididemuqindefuqin':'外公',
  'dididemuqindemuqin':'外婆',
  'dididemuqindegege':'舅父',
  'dididemuqindejiejie':'姨妈',
  'dididemuqindezhangfu':'父亲',
  'dididemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididemuqindedidi':'舅父',
  'dididemuqindemeimei':'姨',
  'dididemuqindeerzi':'比我年长的是哥哥，年小的是弟弟',
  'dididemuqindenver':'比我年长的是姐姐，年小的是妹妹',
  'dididegege':'比我年长的是哥哥，年小的是弟弟',
  'dididegegedefuqin':'父亲',
  'dididegegedemuqin':'母亲',
  'dididegegedegege':'比我年长的是哥哥，年小的是弟弟',
  'dididegegedejiejie':'比我年长的是姐姐，年小的是妹妹',
  'dididegegedeqizi':'比我年长是嫂子，比我年小的是弟媳',
  'dididegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididegegededidi':'比我年长是的哥哥，年小的是弟弟',
  'dididegegedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'dididegegedeerzi':'侄子',
  'dididegegedenver':'侄女',
  'dididejiejie':'比我年长的是姐姐，年小的是妹妹',
  'dididejiejiedefuqin':'父亲',
  'dididejiejiedemuqin':'母亲',
  'dididejiejiedegege':'比我年长的是哥哥，年小的是弟弟',
  'dididejiejiedejiejie':'比我年长的是姐姐，年小的是妹妹',
  'dididejiejiedezhangfu':'比我年长的姐夫，年小的是妹夫',
  'dididejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididejiejiededidi':'比我年长的是哥哥，年小的是弟弟',
  'dididejiejiedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'dididejiejiedeerzi':'外甥',
  'dididejiejiedenver':'外甥女',
  'dididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudefuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudemuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudegege':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudejiejie':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudedidi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudemeimei':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudeerzi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididezhangfudenver':'暂无同性婚姻咨询，你可以按【AC】还原',
  'didideqizi':'弟媳',
  'didideqizidefuqin':'姻世伯',
  'didideqizidemuqin':'姻伯母',
  'didideqizidegege':'比我年长是姻兄，年小的是姻弟',
  'didideqizidejiejie':'比我年长是姻兄，年小的是姻弟',
  'didideqizidezhangfu':'弟弟',
  'didideqizideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'didideqizidedidi':'比我年长是姻兄，年小的是姻弟',
  'didideqizidemeimei':'比我年长是姻姐，年小的是姻妹',
  'didideqizideerzi':'侄子',
  'didideqizidenver':'侄女',
  'dididedidi':'弟弟',
  'dididedididefuqin':'父亲',
  'dididedididemuqin':'母亲',
  'dididedididegege':'比我年长是的哥哥，年小的是弟弟',
  'dididedididejiejie':'比我年长的是姐姐，年小的是妹妹',
  'dididedididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididedidideqizi':'弟媳',
  'dididedididedidi':'弟弟',
  'dididedididemeimei':'没么',
  'dididedidideerzi':'侄子',
  'dididedididenver':'侄女',
  'dididemeimei':'妹妹',
  'dididemeimeidefuqin':'父亲',
  'dididemeimeidemuqin':'母亲',
  'dididemeimeidegege':'比我年长的是哥哥，年小的是弟弟',
  'dididemeimeidejiejie':'比我年长的是姐姐，年小的是妹妹',
  'dididemeimeidezhangfu':'妹夫',
  'dididemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididemeimeidedidi':'弟弟',
  'dididemeimeidemeimei':'妹妹',
  'dididemeimeideerzi':'外甥',
  'dididemeimeidenver':'外甥女',
  'didideerzi':'侄子',
  'didideerzidefuqin':'弟弟',
  'didideerzidemuqin':'弟媳',
  'didideerzidegege':'侄子',
  'didideerzidejiejie':'侄女',
  'didideerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'didideerzideqizi':'侄媳妇',
  'didideerzidedidi':'侄子',
  'didideerzidemeimei':'侄女',
  'didideerzideerzi':'侄孙',
  'didideerzidenver':'侄孙女',
  'dididenver':'侄女',
  'dididenverdefuqin':'弟弟',
  'dididenverdemuqin':'弟媳妇',
  'dididenverdegege':'侄子',
  'dididenverdejiejie':'侄女',
  'dididenverdezhangfu':'侄女婿',
  'dididenverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'dididenverdedidi':'侄子',
  'dididenverdemeimei':'侄女',
  'dididenverdeerzi':'外侄孙',
  'dididenverdenver':'外侄孙女',
  'meimeidefuqin':'父亲',
  'meimeidefuqindefuqin':'爷爷',
  'meimeidefuqindemuqin':'奶奶/嫲嫲',
  'meimeidefuqindegege':'伯父',
  'meimeidefuqindejiejie':'姑妈',
  'meimeidefuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeidefuqindeqizi':'母亲',
  'meimeidefuqindedidi':'叔父',
  'meimeidefuqindemeimei':'姑姐',
  'meimeidefuqindeerzi':'比我年长的是哥哥，年小的是弟弟',
  'meimeidefuqindenver':'比我年长的是姐姐，年小的是妹妹',
  'meimeidemuqin':'母亲',
  'meimeidemuqindefuqin':'外公',
  'meimeidemuqindemuqin':'外婆',
  'meimeidemuqindegege':'舅父',
  'meimeidemuqindejiejie':'姨妈',
  'meimeidemuqindezhangfu':'父亲',
  'meimeidemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeidemuqindedidi':'舅父',
  'meimeidemuqindemeimei':'姨',
  'meimeidemuqindeerzi':'比我年长的是哥哥，年小的是弟弟',
  'meimeidemuqindenver':'比我年长的是姐姐，年小的是妹妹',
  'meimeidegege':'比我年长的是哥哥，年小的是弟弟',
  'meimeidegegedefuqin':'父亲',
  'meimeidegegedemuqin':'母亲',
  'meimeidegegedegege':'比我年长的是哥哥，年小的是弟弟',
  'meimeidegegedejiejie':'比我年长的是姐姐，年小的是妹妹',
  'meimeidegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeidegegedeqizi':'比我年长是嫂子，比我年小的是弟媳',
  'meimeidegegededidi':'比我年长是的哥哥，年小的是弟弟',
  'meimeidegegedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'meimeidegegedeerzi':'侄子',
  'meimeidegegedenver':'侄女',
  'meimeidejiejie':'比我年长的是姐姐，年小的是妹妹',
  'meimeidejiejiedefuqin':'父亲',
  'meimeidejiejiedemuqin':'母亲',
  'meimeidejiejiedegege':'比我年长的哥哥，年小的是弟弟',
  'meimeidejiejiedejiejie':'比我年长的是姐姐，年小的是妹妹',
  'meimeidejiejiedezhangfu':'比我年长的是姐夫，年小的是妹夫',
  'meimeidejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeidejiejiededidi':'比我年长是的哥哥，年小的是弟弟',
  'meimeidejiejiedemeimei':'比我年长的是姐姐，年小的是妹妹',
  'meimeidejiejiedeerzi':'外甥',
  'meimeidejiejiedenver':'外甥女',
  'meimeidezhangfu':'妹夫',
  'meimeidezhangfudefuqin':'姻世伯',
  'meimeidezhangfudemuqin':'姻伯母',
  'meimeidezhangfudegege':'比我年长是姻兄，年小的是姻弟',
  'meimeidezhangfudejiejie':'比我年长是姻姐，年小的是姻妹',
  'meimeidezhangfudezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeidezhangfudeqizi':'妹妹',
  'meimeidezhangfudedidi':'比我年长是姻兄，年小的是姻弟',
  'meimeidezhangfudemeimei':'比我年长是姻姐，年小的是姻妹',
  'meimeidezhangfudeerzi':'外甥',
  'meimeidezhangfudenver':'外甥女',
  'meimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizidefuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizidemuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizidegege':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizidejiejie':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizidedidi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizidemeimei':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizideerzi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideqizidenver':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeidedidi':'弟弟',
  'meimeidedididefuqin':'父亲',
  'meimeidedididemuqin':'母亲',
  'meimeidedididegege':'比我年长是的哥哥，年小的是弟弟',
  'meimeidedididejiejie':'比我年长的是姐姐，年小的是妹妹',
  'meimeidedididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeidedidideqizi':'弟媳妇',
  'meimeidedididedidi':'弟弟',
  'meimeidedididemeimei':'妹妹',
  'meimeidedidideerzi':'侄子',
  'meimeidedididenver':'侄女',
  'meimeidemeimei':'妹妹',
  'meimeidemeimeidefuqin':'父亲',
  'meimeidemeimeidemuqin':'母亲',
  'meimeidemeimeidegege':'比我年长的哥哥，年小的是弟弟',
  'meimeidemeimeidejiejie':'比我年长的是姐姐，年小的是妹妹',
  'meimeidemeimeidezhangfu':'妹夫',
  'meimeidemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeidemeimeidedidi':'弟弟',
  'meimeidemeimeidemeimei':'妹妹',
  'meimeidemeimeideerzi':'外甥',
  'meimeidemeimeidenver':'外甥女',
  'meimeideerzi':'外甥',
  'meimeideerzidefuqin':'妹夫',
  'meimeideerzidemuqin':'妹妹',
  'meimeideerzidegege':'外甥',
  'meimeideerzidejiejie':'外甥女',
  'meimeideerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeideerzideqizi':'外甥媳妇',
  'meimeideerzidedidi':'外甥',
  'meimeideerzidemeimei':'外甥女',
  'meimeideerzideerzi':'外甥孙',
  'meimeideerzidenver':'外甥孙女',
  'meimeidenver':'外甥女',
  'meimeidenverdefuqin':'妹夫',
  'meimeidenverdemuqin':'妹妹',
  'meimeidenverdegege':'外甥',
  'meimeidenverdejiejie':'外甥女',
  'meimeidenverdezhangfu':'外甥女婿',
  'meimeidenverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'meimeidenverdedidi':'外甥',
  'meimeidenverdemeimei':'外甥女',
  'meimeidenverdeerzi':'外甥孙',
  'meimeidenverdenver':'外甥孙女',
  'erzidefuqin':'自己/丈夫',
  'erzidefuqindefuqin':'父亲',
  'erzidefuqindemuqin':'母亲',
  'erzidefuqindegege':'哥哥',
  'erzidefuqindejiejie':'姐姐',
  'erzidefuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidefuqindeqizi':'妻子',
  'erzidefuqindedidi':'弟弟',
  'erzidefuqindemeimei':'妹妹',
  'erzidefuqindeerzi':'儿子',
  'erzidefuqindenver':'女儿',
  'erzidemuqin':'自己/妻子',
  'erzidemuqindefuqin':'女方是叫父亲/男方是叫岳父',
  'erzidemuqindemuqin':'女方是叫母亲/男方是叫岳母',
  'erzidemuqindegege':'女方是叫哥哥/男方是叫大舅',
  'erzidemuqindejiejie':'女方是叫姐姐/男方是叫大姨',
  'erzidemuqindezhangfu':'女方是叫丈夫/男方是自己',
  'erzidemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidemuqindedidi':'女方是叫弟弟/男方是叫舅仔',
  'erzidemuqindemeimei':'女方是叫妹妹/男方是叫姨仔',
  'erzidemuqindeerzi':'儿子',
  'erzidemuqindenver':'女儿',
  'erzidegege':'儿子',
  'erzidegegedefuqin':'女方是叫丈夫/男方是自己',
  'erzidegegedemuqin':'女方是自己/男方是叫妻子',
  'erzidegegedegege':'儿子',
  'erzidegegedejiejie':'女儿',
  'erzidegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidegegedeqizi':'儿媳妇',
  'erzidegegededidi':'儿子',
  'erzidegegedemeimei':'女儿',
  'erzidegegedeerzi':'孙子',
  'erzidegegedenver':'孙女',
  'erzidejiejie':'女儿',
  'erzidejiejiedefuqin':'女方是叫丈夫/男方是自己',
  'erzidejiejiedemuqin':'女方是自己/男方是叫妻子',
  'erzidejiejiedegege':'儿子',
  'erzidejiejiedejiejie':'女儿',
  'erzidejiejiedezhangfu':'女婿',
  'erzidejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidejiejiededidi':'儿子',
  'erzidejiejiedemeimei':'女儿',
  'erzidejiejiedeerzi':'外孙',
  'erzidejiejiedenver':'外孙女',
  'erzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudefuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudemuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudegege':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudejiejie':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudedidi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudemeimei':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudeerzi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidezhangfudenver':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzideqizi':'儿媳妇',
  'erzideqizidefuqin':'亲家公',
  'erzideqizidemuqin':'亲家母',
  'erzideqizidegege':'姻侄',
  'erzideqizidejiejie':'姻侄女',
  'erzideqizidezhangfu':'儿子',
  'erzideqizideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzideqizidedidi':'姻侄',
  'erzideqizidemeimei':'姻侄女',
  'erzideqizideerzi':'孙子',
  'erzideqizidenver':'孙女',
  'erzidedidi':'儿子',
  'erzidedididefuqin':'男方是自己/女方是叫丈夫',
  'erzidedididemuqin':'男方是叫妻子/女方是自己',
  'erzidedididegege':'儿子',
  'erzidedididejiejie':'女儿',
  'erzidedididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidedidideqizi':'儿媳妇',
  'erzidedididedidi':'儿子',
  'erzidedididemeimei':'女儿',
  'erzidedidideerzi':'孙子',
  'erzidedididenver':'孙女',
  'erzidemeimei':'女儿',
  'erzidemeimeidefuqin':'男方是自己/女方是叫丈夫',
  'erzidemeimeidemuqin':'男方是叫妻子/女方是自己',
  'erzidemeimeidegege':'儿子',
  'erzidemeimeidejiejie':'女儿',
  'erzidemeimeidezhangfu':'女婿',
  'erzidemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidemeimeidedidi':'儿子',
  'erzidemeimeidemeimei':'女儿',
  'erzidemeimeideerzi':'外孙',
  'erzidemeimeidenver':'外孙女',
  'erzideerzi':'孙子',
  'erzideerzidefuqin':'儿子',
  'erzideerzidemuqin':'女儿',
  'erzideerzidegege':'孙子',
  'erzideerzidejiejie':'孙女',
  'erzideerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzideerzideqizi':'孙媳妇',
  'erzideerzidedidi':'孙子',
  'erzideerzidemeimei':'孙女',
  'erzideerzideerzi':'曾孙',
  'erzideerzideerzideerzi':'玄孙',
  'erzideerzidenver':'曾孙女',
  'erzideerzidenverdenver':'外玄孙女',
  'erzidenver':'孙女',
  'erzidenverdefuqin':'儿子',
  'erzidenverdemuqin':'女儿',
  'erzidenverdegege':'孙子',
  'erzidenverdejiejie':'孙女',
  'erzidenverdezhangfu':'孙女婿',
  'erzidenverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'erzidenverdedidi':'孙子',
  'erzidenverdemeimei':'孙女',
  'erzidenverdeerzi':'外曾孙',
  'erzidenverdenver':'外曾孙女',
  'erzidenverdeerzi':'外曾玄孙',
  'erzidenverdenver':'外曾玄孙女',
  'nverdefuqin':'自己/丈夫',
  'nverdefuqindefuqin':'父亲',
  'nverdefuqindemuqin':'母亲',
  'nverdefuqindegege':'女方是叫大伯/男方是叫哥哥',
  'nverdefuqindejiejie':'女方是叫大姑/男方是叫姐姐',
  'nverdefuqindezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdefuqindeqizi':'女方是自己/男方是妻子',
  'nverdefuqindedidi':'女方是叫小叔/男方是叫弟弟',
  'nverdefuqindemeimei':'女方是叫小姑/男方是叫妹妹',
  'nverdefuqindeerzi':'儿子',
  'nverdefuqindenver':'女儿',
  'nverdemuqin':'妻子',
  'nverdemuqindefuqin':'女方叫父亲，男方叫岳父',
  'nverdemuqindemuqin':'女方叫母亲，男方叫岳母',
  'nverdemuqindegege':'女方叫哥哥，男方叫大舅',
  'nverdemuqindejiejie':'女方叫姐姐，男方叫大姨',
  'nverdemuqindezhangfu':'女方叫丈夫，男方是自己',
  'nverdemuqindeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdemuqindedidi':'女方叫弟弟，男方叫小舅',
  'nverdemuqindemeimei':'女方叫妹妹，男方叫小姨',
  'nverdemuqindeerzi':'女儿',
  'nverdemuqindenver':'儿子',
  'nverdegege':'儿子',
  'nverdegegedefuqin':'女方叫丈夫，男方是自己',
  'nverdegegedemuqin':'女方是自己，男方叫妻子',
  'nverdegegedegege':'儿子',
  'nverdegegedejiejie':'女儿',
  'nverdegegedezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdegegedeqizi':'儿媳妇',
  'nverdegegededidi':'儿子',
  'nverdegegedemeimei':'女儿',
  'nverdegegedeerzi':'孙子',
  'nverdegegedenver':'孙女',
  'nverdejiejie':'女儿',
  'nverdejiejiedefuqin':'女方叫丈夫，男方是自己',
  'nverdejiejiedemuqin':'女方是自己，男方叫妻子',
  'nverdejiejiedegege':'儿子',
  'nverdejiejiedejiejie':'女儿',
  'nverdejiejiedezhangfu':'女婿',
  'nverdejiejiedeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdejiejiededidi':'儿子',
  'nverdejiejiedemeimei':'女儿',
  'nverdejiejiedeerzi':'外孙',
  'nverdejiejiedenver':'外孙女',
  'nverdezhangfu':'女婿',
  'nverdezhangfudefuqin':'亲家公',
  'nverdezhangfudemuqin':'亲家母',
  'nverdezhangfudegege':'姻侄',
  'nverdezhangfudejiejie':'姻侄女',
  'nverdezhangfudezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdezhangfudeqizi':'女儿',
  'nverdezhangfudedidi':'姻侄',
  'nverdezhangfudemeimei':'姻侄',
  'nverdezhangfudeerzi':'外孙',
  'nverdezhangfudenver':'外孙女',
  'nverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizidefuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizidemuqin':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizidegege':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizidejiejie':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizidedidi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizidemeimei':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizideerzi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeqizidenver':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdedidi':'小儿子',
  'nverdedididefuqin':'女方叫丈夫，男方是自己',
  'nverdedididemuqin':'女方是自己，男方叫妻子',
  'nverdedididegege':'儿子',
  'nverdedididejiejie':'女儿',
  'nverdedididezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdedidideqizi':'儿媳妇',
  'nverdedididedidi':'小儿子',
  'nverdedididemeimei':'小女儿',
  'nverdedidideerzi':'孙子',
  'nverdedididenver':'孙女',
  'nverdemeimei':'小女儿',
  'nverdemeimeidefuqin':'女方叫丈夫，男方是自己',
  'nverdemeimeidemuqin':'女方是自己，男方叫妻子',
  'nverdemeimeidegege':'儿子',
  'nverdemeimeidejiejie':'女儿',
  'nverdemeimeidezhangfu':'女婿',
  'nverdemeimeideqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdemeimeidedidi':'小儿子',
  'nverdemeimeidemeimei':'小女儿',
  'nverdemeimeideerzi':'外孙',
  'nverdemeimeidenver':'外孙女',
  'nverdeerzi':'外孙',
  'nverdeerzidefuqin':'女婿',
  'nverdeerzidemuqin':'女儿',
  'nverdeerzidegege':'外孙',
  'nverdeerzidejiejie':'外孙女',
  'nverdeerzidezhangfu':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdeerzideqizi':'外孙媳妇',
  'nverdeerzideerzideqizi':'外玄孙媳妇',
  'nverdeerzidedidi':'外孙',
  'nverdeerzidemeimei':'外孙女',
  'nverdeerzideerzi':'外曾孙',
  'nverdeerzidenver':'外曾孙女',
  'nverdenver':'外孙女',
  'nverdenverdefuqin':'女婿',
  'nverdenverdemuqin':'女儿',
  'nverdenverdegege':'外孙',
  'nverdenverdejiejie':'外孙女',
  'nverdenverdezhangfu':'外孙女婿',
  'nverdenverdedenverzhangfu':'外玄孙女婿',
  'nverdenverdeqizi':'暂无同性婚姻咨询，你可以按【AC】还原',
  'nverdenverdedidi':'外孙',
  'nverdenverdemeimei':'外孙女',
  'nverdenverdeerzi':'外曾孙',
  'nverdenverdenver':'外曾孙女',
  'wodefuqindefuqindefuqin': '太公',
  'wodefuqindefuqindemuqin': '太婆',
  'wodefuqindefuqindegege': '伯公',
  'wodefuqindefuqindejiejie': '姑婆',
  'wodefuqindefuqindezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindefuqindeqizi': '奶奶/嫲嫲',
  'wodefuqindefuqindedidi': '叔公',
  'wodefuqindefuqindemeimei': '姑婆',
  'wodefuqindefuqindeerzi': '比父亲年长的是伯父，年小的是叔父',
  'wodefuqindefuqindenver': '比父亲年长的是姑妈，年小的是姑姐',
  'wodefuqindemuqindefuqin': '外太公',
  'wodefuqindemuqindemuqin': '外太婆',
  'wodefuqindemuqindegege': '舅公',
  'wodefuqindemuqindejiejie': '姨婆',
  'wodefuqindemuqindezhangfu': '爷爷',
  'wodefuqindemuqindeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindemuqindedidi': '舅公',
  'wodefuqindemuqindemeimei': '姨婆',
  'wodefuqindemuqindeerzi': '比父亲年长的是伯父，年小的是叔父',
  'wodefuqindemuqindenver': '比父亲年长的是姑妈，年小的是姑姐',
  'wodefuqindegegedefuqin': '爷爷',
  'wodefuqindegegedemuqin': '奶奶/嫲嫲',
  'wodefuqindegegedegege': '伯父',
  'wodefuqindegegedejiejie': '姑妈',
  'wodefuqindegegedezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindegegedeqizi': '伯娘',
  'wodefuqindegegededidi': '比父亲年长的是伯父，年小的是叔父',
  'wodefuqindegegedemeimei': '比父亲年长的是姑妈，年小的是姑姐',
  'wodefuqindegegedeerzi': '比我年长是堂兄，年小的是堂弟',
  'wodefuqindegegedenver': '比我年长是堂姐，年小的是堂妹',
  'wodefuqindejiejiedefuqin': '爷爷',
  'wodefuqindejiejiedemuqin': '奶奶/嫲嫲',
  'wodefuqindejiejiedegege': '伯父',
  'wodefuqindejiejiedejiejie': '姑妈',
  'wodefuqindejiejiedezhangfu': '姑丈',
  'wodefuqindejiejiedeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindejiejiededidi': '比父亲年长的是伯父，年小的是叔父',
  'wodefuqindejiejiedemeimei': '比父亲年长的是姑妈，年小的是姑姐',
  'wodefuqindejiejiedeerzi': '比我年长【姑】表兄，年小【姑】表弟',
  'wodefuqindejiejiedenver': '比我年长【姑】表姐，年小【姑】表妹',
  'wodefuqindezhangfudefuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindezhangfudemuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindezhangfudegege': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindezhangfudejiejie': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindezhangfudezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindezhangfudeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindezhangfudedidi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindezhangfudemeimei': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindezhangfudeerzi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindezhangfudenver': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindeqizidefuqin': '外公',
  'wodefuqindeqizidemuqin': '外婆',
  'wodefuqindeqizidegege': '舅父',
  'wodefuqindeqizidejiejie': '姨妈',
  'wodefuqindeqizidezhangfu': '父亲',
  'wodefuqindeqizideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindeqizidedidi': '舅父',
  'wodefuqindeqizidemeimei': '姨',
  'wodefuqindeqizideerzi': '比我年小的是弟弟，年长的是哥哥',
  'wodefuqindeqizidenver': '比我年小的是妹妹，年长的是姐姐',
  'wodefuqindedididefuqin': '爷爷',
  'wodefuqindedididemuqin': '奶奶/嫲嫲',
  'wodefuqindedididegege': '比父亲年小的是叔父，年长的是伯父',
  'wodefuqindedididejiejie': '比父亲年小的是姑姐，年长的是姑妈',
  'wodefuqindedididezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindedidideqizi': '嬸',
  'wodefuqindedididedidi': '叔父',
  'wodefuqindedididemeimei': '姑姐',
  'wodefuqindedidideerzi': '比我年长是堂兄，年小的是堂弟',
  'wodefuqindedididenver': '比我年长是堂姐，年小的是堂妹',
  'wodefuqindemeimeidefuqin': '爷爷',
  'wodefuqindemeimeidemuqin': '奶奶/嫲嫲',
  'wodefuqindemeimeidegege': '比父亲年长的是伯父，年小的是叔父',
  'wodefuqindemeimeidejiejie': '比父亲年长的是姑妈，年小的是姑姐',
  'wodefuqindemeimeidezhangfu': '姑丈',
  'wodefuqindemeimeideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindemeimeidedidi': '叔父',
  'wodefuqindemeimeidemeimei': '姑姐',
  'wodefuqindemeimeideerzi': '比我年长【姑】表兄，年小【姑】表弟',
  'wodefuqindemeimeidenver': '比我年长【姑】表姐，年小【姑】表妹',
  'wodefuqindeerzidefuqin': '父亲',
  'wodefuqindeerzidemuqin': '母亲',
  'wodefuqindeerzidegege': '比我年小的是弟弟，年长的是哥哥',
  'wodefuqindeerzidejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodefuqindeerzidezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindeerzideqizi': '比我年长是嫂子，年小的是弟媳',
  'wodefuqindeerzidedidi': '比我年小的是弟弟，年长的是哥哥',
  'wodefuqindeerzidemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodefuqindeerzideerzi': '侄子',
  'wodefuqindeerzidenver': '侄女',
  'wodefuqindenverdefuqin': '父亲',
  'wodefuqindenverdemuqin': '母亲',
  'wodefuqindenverdegege': '比我年小的是弟弟，年长的是哥哥',
  'wodefuqindenverdejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodefuqindenverdezhangfu': '比我年长是姐夫，年小是妹夫',
  'wodefuqindenverdeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodefuqindenverdedidi': '比我年小的是弟弟，年长的是哥哥',
  'wodefuqindenverdemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodefuqindenverdeerzi': '外甥',
  'wodefuqindenverdenver': '外甥女',
  'wodemuqindefuqindefuqin': '外太公',
  'wodemuqindefuqindemuqin': '外太婆',
  'wodemuqindefuqindegege': '外伯公',
  'wodemuqindefuqindejiejie': '外姑婆',
  'wodemuqindefuqindezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindefuqindeqizi': '外婆',
  'wodemuqindefuqindedidi': '外叔公',
  'wodemuqindefuqindemeimei': '外姑婆',
  'wodemuqindefuqindeerzi': '舅父',
  'wodemuqindefuqindenver': '比母亲年长是姨妈，年小是姨',
  'wodemuqindemuqindefuqin': '外太外公',
  'wodemuqindemuqindemuqin': '外太外婆',
  'wodemuqindemuqindegege': '外舅公',
  'wodemuqindemuqindejiejie': '外姨婆',
  'wodemuqindemuqindezhangfu': '外公',
  'wodemuqindemuqindeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindemuqindedidi': '外舅公',
  'wodemuqindemuqindemeimei': '外姨婆',
  'wodemuqindemuqindeerzi': '舅父',
  'wodemuqindemuqindenver': '比母亲年长是姨妈，年小是姨',
  'wodemuqindegegedefuqin': '外公',
  'wodemuqindegegedemuqin': '外婆',
  'wodemuqindegegedegege': '舅父',
  'wodemuqindegegedejiejie': '比母亲年长是姨妈，年小是姨',
  'wodemuqindegegedezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindegegedeqizi': '舅母',
  'wodemuqindegegededidi': '舅父',
  'wodemuqindegegedemeimei': '比母亲年长是姨妈，年小是姨',
  'wodemuqindegegedeerzi': '比我年长【舅】表兄，年小的是【舅】表弟',
  'wodemuqindegegedenver': '比我年长【舅】表姐，年小的是【舅】表妹',
  'wodemuqindejiejiedefuqin': '外公',
  'wodemuqindejiejiedemuqin': '外婆',
  'wodemuqindejiejiedegege': '舅父',
  'wodemuqindejiejiedejiejie': '姨妈',
  'wodemuqindejiejiedezhangfu': '姨丈',
  'wodemuqindejiejiedeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindejiejiededidi': '舅父',
  'wodemuqindejiejiedemeimei': '比母亲年长是姨妈，年小是姨',
  'wodemuqindejiejiedeerzi': '比我年长【舅】表兄，年小的是【舅】表弟',
  'wodemuqindejiejiedenver': '比我年长【舅】表姐，年小的是【舅】表妹',
  'wodemuqindezhangfudefuqin': '爷爷',
  'wodemuqindezhangfudemuqin': '奶奶/嫲嫲',
  'wodemuqindezhangfudegege': '伯父',
  'wodemuqindezhangfudejiejie': '姑妈',
  'wodemuqindezhangfudezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindezhangfudeqizi': '母亲',
  'wodemuqindezhangfudedidi': '叔父',
  'wodemuqindezhangfudemeimei': '姑姐',
  'wodemuqindezhangfudeerzi': '比我年小的是弟弟，年长的是哥哥',
  'wodemuqindezhangfudenver': '比我年小的是妹妹，年长的是姐姐',
  'wodemuqindeqizidefuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeqizidemuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeqizidegege': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeqizidejiejie': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeqizidezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeqizideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeqizidedidi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeqizidemeimei': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeqizideerzi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeqizidenver': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindedididefuqin': '外公',
  'wodemuqindedididemuqin': '外婆',
  'wodemuqindedididegege': '舅父',
  'wodemuqindedididejiejie': '比母亲年长是姨妈，年小是姨',
  'wodemuqindedididezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindedidideqizi': '舅母',
  'wodemuqindedididedidi': '舅父',
  'wodemuqindedididemeimei': '比母亲年长是姨妈，年小是姨',
  'wodemuqindedidideerzi': '比我年长【舅】表兄，年小的是【舅】表弟',
  'wodemuqindedididenver': '比我年长【舅】表姐，年小的是【舅】表妹',
  'wodemuqindemeimeidefuqin': '外公',
  'wodemuqindemeimeidemuqin': '外婆',
  'wodemuqindemeimeidegege': '舅父',
  'wodemuqindemeimeidejiejie': '比母亲年长是姨妈，年小是姨',
  'wodemuqindemeimeidezhangfu': '姨丈',
  'wodemuqindemeimeideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindemeimeidedidi': '舅父',
  'wodemuqindemeimeidemeimei': '姨',
  'wodemuqindemeimeideerzi': '比我年长【姨】表兄，年小的是【姨】表弟',
  'wodemuqindemeimeidenver': '比我年长【姨】表姐，年小的是【姨】表妹',
  'wodemuqindeerzidefuqin': '父亲',
  'wodemuqindeerzidemuqin': '母亲',
  'wodemuqindeerzidegege': '比我年小的是弟弟，年长的是哥哥',
  'wodemuqindeerzidejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodemuqindeerzidezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindeerzideqizi': '比我年长是嫂子，年小的是弟媳',
  'wodemuqindeerzidedidi': '比我年小的是弟弟，年长的是哥哥',
  'wodemuqindeerzidemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodemuqindeerzideerzi': '侄子',
  'wodemuqindeerzidenver': '侄女',
  'wodemuqindenverdefuqin': '父亲',
  'wodemuqindenverdemuqin': '母亲',
  'wodemuqindenverdegege': '比我年小的是弟弟，年长的是哥哥',
  'wodemuqindenverdejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodemuqindenverdezhangfu': '比我年长的姐夫，年小的是妹夫',
  'wodemuqindenverdeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemuqindenverdedidi': '比我年小的是弟弟，年长的是哥哥',
  'wodemuqindenverdemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodemuqindenverdeerzi': '外甥',
  'wodemuqindenverdenver': '外甥女',
  'wodegegedefuqindefuqin': '爷爷',
  'wodegegedefuqindemuqin': '奶奶/嫲嫲',
  'wodegegedefuqindegege': '伯父',
  'wodegegedefuqindejiejie': '姑妈',
  'wodegegedefuqindezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedefuqindeqizi': '母亲',
  'wodegegedefuqindedidi': '叔父',
  'wodegegedefuqindemeimei': '姑姐',
  'wodegegedefuqindeerzi': '比我年小的是弟弟，年长的是哥哥',
  'wodegegedefuqindenver': '比我年小的是妹妹，年长的是姐姐',
  'wodegegedemuqindefuqin': '外公',
  'wodegegedemuqindemuqin': '外婆',
  'wodegegedemuqindegege': '舅父',
  'wodegegedemuqindejiejie': '姨妈',
  'wodegegedemuqindezhangfu': '父亲',
  'wodegegedemuqindeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedemuqindedidi': '舅父',
  'wodegegedemuqindemeimei': '姨',
  'wodegegedemuqindeerzi': '比我年小的是弟弟，年长的是哥哥',
  'wodegegedemuqindenver': '比我年小的是妹妹，年长的是姐姐',
  'wodegegedegegedefuqin': '父亲',
  'wodegegedegegedemuqin': '母亲',
  'wodegegedegegedegege': '哥哥',
  'wodegegedegegedejiejie': '姐姐',
  'wodegegedegegedezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedegegedeqizi': '大嫂',
  'wodegegedegegededidi': '比我年小的是弟弟，年长的是哥哥',
  'wodegegedegegedemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodegegedegegedeerzi': '侄子',
  'wodegegedegegedenver': '侄女',
  'wodegegedejiejiedefuqin': '父亲',
  'wodegegedejiejiedemuqin': '母亲',
  'wodegegedejiejiedegege': '哥哥',
  'wodegegedejiejiedejiejie': '姐姐',
  'wodegegedejiejiedezhangfu': '姐夫',
  'wodegegedejiejiedeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedejiejiededidi': '比我年小的是弟弟，年长的是哥哥',
  'wodegegedejiejiedemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodegegedejiejiedeerzi': '外甥',
  'wodegegedejiejiedenver': '外甥女',
  'wodegegedezhangfudefuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedezhangfudemuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedezhangfudegege': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedezhangfudejiejie': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedezhangfudezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedezhangfudeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedezhangfudedidi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedezhangfudemeimei': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedezhangfudeerzi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedezhangfudenver': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedeqizidefuqin': '姻世伯',
  'wodegegedeqizidemuqin': '姻伯母',
  'wodegegedeqizidegege': '比我年长是姻兄，年小的是姻弟',
  'wodegegedeqizidejiejie': '比我年长是姻姐，年小的是姻妹',
  'wodegegedeqizidezhangfu': '哥哥',
  'wodegegedeqizideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedeqizidedidi': '比我年长是姻兄，年小的是姻弟',
  'wodegegedeqizidemeimei': '比我年长是姻姐，年小的是姻妹',
  'wodegegedeqizideerzi': '侄子',
  'wodegegedeqizidenver': '侄女',
  'wodegegededididefuqin': '父亲',
  'wodegegededididemuqin': '母亲',
  'wodegegededididegege': '比我年小的是弟弟，年长的是哥哥',
  'wodegegededididejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodegegededididezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegededidideqizi': '弟媳',
  'wodegegededididedidi': '比我年小的是弟弟，年长的是哥哥',
  'wodegegededididemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodegegededidideerzi': '侄子',
  'wodegegededididenver': '侄女',
  'wodegegedemeimeidefuqin': '父亲',
  'wodegegedemeimeidemuqin': '母亲',
  'wodegegedemeimeidegege': '比我年小的是弟弟，年长的是哥哥',
  'wodegegedemeimeidejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodegegedemeimeidezhangfu': '妹夫',
  'wodegegedemeimeideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedemeimeidedidi': '比我年小的是弟弟，年长的是哥哥',
  'wodegegedemeimeidemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodegegedemeimeideerzi': '外甥',
  'wodegegedemeimeidenver': '外甥女',
  'wodegegedeerzidefuqin': '哥哥',
  'wodegegedeerzidemuqin': '嫂子',
  'wodegegedeerzidegege': '侄子',
  'wodegegedeerzidejiejie': '侄女',
  'wodegegedeerzidezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedeerzideqizi': '侄媳妇',
  'wodegegedeerzidedidi': '侄子',
  'wodegegedeerzidemeimei': '侄女',
  'wodegegedeerzideerzi': '侄孙',
  'wodegegedeerzidenver': '侄孙女',
  'wodegegedenverdefuqin': '哥哥',
  'wodegegedenverdemuqin': '嫂子',
  'wodegegedenverdegege': '侄子',
  'wodegegedenverdejiejie': '侄女',
  'wodegegedenverdezhangfu': '侄女婿',
  'wodegegedenverdeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodegegedenverdedidi': '侄子',
  'wodegegedenverdemeimei': '侄女',
  'wodegegedenverdeerzi': '外侄孙',
  'wodegegedenverdenver': '外侄孙女',
  'wodejiejiedefuqindefuqin': '爷爷',
  'wodejiejiedefuqindemuqin': '奶奶/嫲嫲',
  'wodejiejiedefuqindegege': '伯父',
  'wodejiejiedefuqindejiejie': '姑妈',
  'wodejiejiedefuqindezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedefuqindeqizi': '母亲',
  'wodejiejiedefuqindedidi': '叔父',
  'wodejiejiedefuqindemeimei': '姑姐',
  'wodejiejiedefuqindeerzi': '比我年小的是弟弟，年长的是哥哥',
  'wodejiejiedefuqindenver': '比我年小的是妹妹，年长的是姐姐',
  'wodejiejiedemuqindefuqin': '外公',
  'wodejiejiedemuqindemuqin': '外婆',
  'wodejiejiedemuqindegege': '舅父',
  'wodejiejiedemuqindejiejie': '姨妈',
  'wodejiejiedemuqindezhangfu': '父亲',
  'wodejiejiedemuqindeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedemuqindedidi': '舅父',
  'wodejiejiedemuqindemeimei': '姨',
  'wodejiejiedemuqindeerzi': '比我年小的是弟弟，年长的是哥哥',
  'wodejiejiedemuqindenver': '比我年小的是妹妹，年长的是姐姐',
  'wodejiejiedegegedefuqin': '父亲',
  'wodejiejiedegegedemuqin': '父亲',
  'wodejiejiedegegedegege': '哥哥',
  'wodejiejiedegegedejiejie': '姐姐',
  'wodejiejiedegegedezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedegegedeqizi': '嫂子',
  'wodejiejiedegegededidi': '比我年小的是弟弟，年长的是哥哥',
  'wodejiejiedegegedemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodejiejiedegegedeerzi': '侄子',
  'wodejiejiedegegedenver': '侄女',
  'wodejiejiedejiejiedefuqin': '父亲',
  'wodejiejiedejiejiedemuqin': '母亲',
  'wodejiejiedejiejiedegege': '哥哥',
  'wodejiejiedejiejiedejiejie': '姐姐',
  'wodejiejiedejiejiedezhangfu': '姐夫',
  'wodejiejiedejiejiedeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedejiejiededidi': '比我年小的是弟弟，年长的是哥哥',
  'wodejiejiedejiejiedemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodejiejiedejiejiedeerzi': '外甥',
  'wodejiejiedejiejiedenver': '外甥女',
  'wodejiejiedezhangfudefuqin': '姻世伯',
  'wodejiejiedezhangfudemuqin': '姻伯母',
  'wodejiejiedezhangfudegege': '比我年长是姻兄，年小的是姻弟',
  'wodejiejiedezhangfudejiejie': '比我年长是姻姐，年小的是姻妹',
  'wodejiejiedezhangfudezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedezhangfudeqizi': '姐姐',
  'wodejiejiedezhangfudedidi': '比我年长是姻兄，年小的是姻弟',
  'wodejiejiedezhangfudemeimei': '比我年长是姻姐，年小的是姻妹',
  'wodejiejiedezhangfudeerzi': '外甥',
  'wodejiejiedezhangfudenver': '外甥女',
  'wodejiejiedeqizidefuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeqizidemuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeqizidegege': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeqizidejiejie': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeqizidezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeqizideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeqizidedidi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeqizidemeimei': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeqizideerzi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeqizidenver': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiededididefuqin': '父亲',
  'wodejiejiededididemuqin': '母亲',
  'wodejiejiededididegege': '比我年长是的哥哥，年小的是弟弟',
  'wodejiejiededididejiejie': '比我年长的是姐姐，年小的是妹妹',
  'wodejiejiededididezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiededidideqizi': '弟媳妇',
  'wodejiejiededididedidi': '比我年长的是哥哥，年小的是弟弟',
  'wodejiejiededididemeimei': '比我年长的是姐姐，年小的是妹妹',
  'wodejiejiededidideerzi': '侄子',
  'wodejiejiededididenver': '侄女',
  'wodejiejiedemeimeidefuqin': '父亲',
  'wodejiejiedemeimeidemuqin': '母亲',
  'wodejiejiedemeimeidegege': '比我年长的是哥哥，年小的是弟弟',
  'wodejiejiedemeimeidejiejie': '比我年长的是姐姐，年小的是妹妹',
  'wodejiejiedemeimeidezhangfu': '妹夫',
  'wodejiejiedemeimeideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedemeimeidedidi': '比我年长的是哥哥，年小的是弟弟',
  'wodejiejiedemeimeidemeimei': '比我年长的是姐姐，年小的是妹妹',
  'wodejiejiedemeimeideerzi': '外甥',
  'wodejiejiedemeimeidenver': '外甥女',
  'wodejiejiedeerzidefuqin': '姐夫',
  'wodejiejiedeerzidemuqin': '姐姐',
  'wodejiejiedeerzidegege': '外甥',
  'wodejiejiedeerzidejiejie': '外甥女',
  'wodejiejiedeerzidezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedeerzideqizi': '外甥媳妇',
  'wodejiejiedeerzidedidi': '外甥',
  'wodejiejiedeerzidemeimei': '外甥女',
  'wodejiejiedeerzideerzi': '外甥孙',
  'wodejiejiedeerzidenver': '外甥孙女',
  'wodejiejiedenverdefuqin': '姐夫',
  'wodejiejiedenverdemuqin': '姐姐',
  'wodejiejiedenverdegege': '外甥',
  'wodejiejiedenverdejiejie': '外甥女',
  'wodejiejiedenverdezhangfu': '外甥女婿',
  'wodejiejiedenverdeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodejiejiedenverdedidi': '外甥',
  'wodejiejiedenverdemeimei': '外甥女',
  'wodejiejiedenverdeerzi': '外甥孙',
  'wodejiejiedenverdenver': '外甥孙女',
  'wodedididefuqindefuqin': '爷爷',
  'wodedididefuqindemuqin': '奶奶/嫲嫲',
  'wodedididefuqindegege': '伯父',
  'wodedididefuqindejiejie': '姑妈',
  'wodedididefuqindezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididefuqindeqizi': '母亲',
  'wodedididefuqindedidi': '叔父',
  'wodedididefuqindemeimei': '姑姐',
  'wodedididefuqindeerzi': '比我年长的是哥哥，年小的是弟弟',
  'wodedididefuqindenver': '比我年长的是姐姐，年小的是妹妹',
  'wodedididemuqindefuqin': '外公',
  'wodedididemuqindemuqin': '外婆',
  'wodedididemuqindegege': '舅父',
  'wodedididemuqindejiejie': '姨妈',
  'wodedididemuqindezhangfu': '父亲',
  'wodedididemuqindeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididemuqindedidi': '舅父',
  'wodedididemuqindemeimei': '姨',
  'wodedididemuqindeerzi': '比我年长的哥哥，年小的是弟弟',
  'wodedididemuqindenver': '比我年长的是姐姐，年小的是妹妹',
  'wodedididegegedefuqin': '父亲',
  'wodedididegegedemuqin': '母亲',
  'wodedididegegedegege': '比我年长的是哥哥，年小的是弟弟',
  'wodedididegegedejiejie': '比我年长的是姐姐，年小的是妹妹',
  'wodedididegegedezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididegegedeqizi': '比我年长是嫂子，比我年小的是弟媳',
  'wodedididegegededidi': '比我年长是的哥哥，年小的是弟弟',
  'wodedididegegedemeimei': '比我年长的是姐姐，年小的是妹妹',
  'wodedididegegedeerzi': '侄子',
  'wodedididegegedenver': '侄女',
  'wodedididejiejiedefuqin': '父亲',
  'wodedididejiejiedemuqin': '母亲',
  'wodedididejiejiedegege': '比我年长的是哥哥，年小的是弟弟',
  'wodedididejiejiedejiejie': '比我年长的是姐姐，年小的是妹妹',
  'wodedididejiejiedezhangfu': '比我年长的是姐夫，年小的是妹夫',
  'wodedididejiejiedeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididejiejiededidi': '比我年长的哥哥，年小的是弟弟',
  'wodedididejiejiedemeimei': '比我年长的是姐姐，年小的是妹妹',
  'wodedididejiejiedeerzi': '姨甥',
  'wodedididejiejiedenver': '姨甥女',
  'wodedididezhangfudefuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididezhangfudemuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididezhangfudegege': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididezhangfudejiejie': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididezhangfudezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididezhangfudeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididezhangfudedidi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididezhangfudemeimei': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididezhangfudeerzi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididezhangfudenver': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedidideqizidefuqin': '姻世伯',
  'wodedidideqizidemuqin': '姻伯母',
  'wodedidideqizidegege': '比我年长是姻兄，年小的是姻弟',
  'wodedidideqizidejiejie': '比我年长是姻姐，年小的是姻妹',
  'wodedidideqizidezhangfu': '弟弟',
  'wodedidideqizideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedidideqizidedidi': '比我年长是姻兄，年小的是姻弟',
  'wodedidideqizidemeimei': '比我年长是姻姐，年小的是姻妹',
  'wodedidideqizideerzi': '侄子',
  'wodedidideqizidenver': '侄女',
  'wodedididedididefuqin': '父亲',
  'wodedididedididemuqin': '母亲',
  'wodedididedididegege': '比我年小的是弟弟，年长的是哥哥',
  'wodedididedididejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodedididedididezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididedidideqizi': '弟媳妇',
  'wodedididedididedidi': '弟弟',
  'wodedididedididemeimei': '妹妹',
  'wodedididedidideerzi': '侄子',
  'wodedididedididenver': '侄女',
  'wodedididemeimeidefuqin': '父亲',
  'wodedididemeimeidemuqin': '母亲',
  'wodedididemeimeidegege': '比我年小的是弟弟，年长的是哥哥',
  'wodedididemeimeidejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodedididemeimeidezhangfu': '妹夫',
  'wodedididemeimeideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididemeimeidedidi': '弟弟',
  'wodedididemeimeidemeimei': '妹妹',
  'wodedididemeimeideerzi': '姨甥',
  'wodedididemeimeidenver': '姨甥女',
  'wodedidideerzidefuqin': '弟弟',
  'wodedidideerzidemuqin': '弟媳妇',
  'wodedidideerzidegege': '侄子',
  'wodedidideerzidejiejie': '侄女',
  'wodedidideerzidezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedidideerzideqizi': '侄媳妇',
  'wodedidideerzidedidi': '侄子',
  'wodedidideerzidemeimei': '侄女',
  'wodedidideerzideerzi': '侄孙',
  'wodedidideerzidenver': '侄孙女',
  'wodedididenverdefuqin': '弟弟',
  'wodedididenverdemuqin': '弟媳妇',
  'wodedididenverdegege': '侄子',
  'wodedididenverdejiejie': '侄女',
  'wodedididenverdezhangfu': '侄女婿',
  'wodedididenverdeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodedididenverdedidi': '侄子',
  'wodedididenverdemeimei': '侄女',
  'wodedididenverdeerzi': '外侄孙',
  'wodedididenverdenver': '外侄孙女',
  'wodemeimeidefuqindefuqin': '爷爷',
  'wodemeimeidefuqindemuqin': '奶奶/嫲嫲',
  'wodemeimeidefuqindegege': '伯父',
  'wodemeimeidefuqindejiejie': '姑妈',
  'wodemeimeidefuqindezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidefuqindeqizi': '母亲',
  'wodemeimeidefuqindedidi': '叔父',
  'wodemeimeidefuqindemeimei': '姑姐',
  'wodemeimeidefuqindeerzi': '比我年小的是弟弟，年长的是哥哥',
  'wodemeimeidefuqindenver': '比我年小的是妹妹，年长的是姐姐',
  'wodemeimeidemuqindefuqin': '外公',
  'wodemeimeidemuqindemuqin': '外婆',
  'wodemeimeidemuqindegege': '舅父',
  'wodemeimeidemuqindejiejie': '姨妈',
  'wodemeimeidemuqindezhangfu': '父亲',
  'wodemeimeidemuqindeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidemuqindedidi': '舅父',
  'wodemeimeidemuqindemeimei': '姨',
  'wodemeimeidemuqindeerzi': '比我年小的是弟弟，年长的是哥哥',
  'wodemeimeidemuqindenver': '比我年小的是妹妹，年长的是姐姐',
  'wodemeimeidegegedefuqin': '父亲',
  'wodemeimeidegegedemuqin': '母亲',
  'wodemeimeidegegedegege': '比我年小的是弟弟，年长的是哥哥',
  'wodemeimeidegegedejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodemeimeidegegedezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidegegedeqizi': '比我年长是嫂子，年小的是弟媳',
  'wodemeimeidegegededidi': '比我年小的是弟弟，年长的是哥哥',
  'wodemeimeidegegedemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodemeimeidegegedeerzi': '侄子',
  'wodemeimeidegegedenver': '侄女',
  'wodemeimeidejiejiedefuqin': '父亲',
  'wodemeimeidejiejiedemuqin': '母亲',
  'wodemeimeidejiejiedegege': '比我年小的是弟弟，年长的是哥哥',
  'wodemeimeidejiejiedejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodemeimeidejiejiedezhangfu': '比我年长是姐夫，年小是妹夫',
  'wodemeimeidejiejiedeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidejiejiededidi': '比我年小的是弟弟，年长的是哥哥',
  'wodemeimeidejiejiedemeimei': '比我年小的是妹妹，年长的是姐姐',
  'wodemeimeidejiejiedeerzi': '姨甥',
  'wodemeimeidejiejiedenver': '姨甥女',
  'wodemeimeidezhangfudefuqin': '姻世伯',
  'wodemeimeidezhangfudemuqin': '姻伯母',
  'wodemeimeidezhangfudegege': '比我年长是姻兄，年小的是姻弟',
  'wodemeimeidezhangfudejiejie': '比我年长是姻姐，年小的是姻妹',
  'wodemeimeidezhangfudezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidezhangfudeqizi': '妹妹',
  'wodemeimeidezhangfudedidi': '比我年长是姻兄，年小的是姻弟',
  'wodemeimeidezhangfudemeimei': '比我年长是姻姐，年小的是姻妹',
  'wodemeimeidezhangfudeerzi': '姨甥',
  'wodemeimeidezhangfudenver': '姨甥女',
  'wodemeimeideqizidefuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideqizidemuqin': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideqizidegege': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideqizidejiejie': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideqizidezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideqizideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideqizidedidi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideqizidemeimei': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideqizideerzi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideqizidenver': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidedididefuqin': '父亲',
  'wodemeimeidedididemuqin': '母亲',
  'wodemeimeidedididegege': '比我年小的是弟弟，年长的是哥哥',
  'wodemeimeidedididejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodemeimeidedididezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidedidideqizi': '弟媳妇',
  'wodemeimeidedididedidi': '弟弟',
  'wodemeimeidedididemeimei': '妹妹',
  'wodemeimeidedidideerzi': '侄子',
  'wodemeimeidedididenver': '侄女',
  'wodemeimeidemeimeidefuqin': '父亲',
  'wodemeimeidemeimeidemuqin': '母亲',
  'wodemeimeidemeimeidegege': '比我年小的是弟弟，年长的是哥哥',
  'wodemeimeidemeimeidejiejie': '比我年小的是妹妹，年长的是姐姐',
  'wodemeimeidemeimeidezhangfu': '妹夫',
  'wodemeimeidemeimeideqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidemeimeidedidi': '弟弟',
  'wodemeimeidemeimeidemeimei': '妹妹',
  'wodemeimeidemeimeideerzi': '姨甥',
  'wodemeimeidemeimeidenver': '姨甥女',
  'wodemeimeideerzidefuqin': '妹夫',
  'wodemeimeideerzidemuqin': '妹妹',
  'wodemeimeideerzidegege': '姨甥',
  'wodemeimeideerzidejiejie': '姨甥女',
  'wodemeimeideerzidezhangfu': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeideerzideqizi': '姨甥媳妇',
  'wodemeimeideerzidedidi': '姨甥',
  'wodemeimeideerzidemeimei': '姨甥女',
  'wodemeimeideerzideerzi': '姨甥孙',
  'wodemeimeideerzidenver': '姨甥孙女',
  'wodemeimeidenverdefuqin': '妹夫',
  'wodemeimeidenverdemuqin': '妹妹',
  'wodemeimeidenverdegege': '姨甥',
  'wodemeimeidenverdejiejie': '姨甥女',
  'wodemeimeidenverdezhangfu': '姨甥女婿',
  'wodemeimeidenverdeqizi': '暂无同性婚姻咨询，你可以按【AC】还原',
  'wodemeimeidenverdedidi': '姨甥',
  'wodemeimeidenverdemeimei': '姨甥女',
  'wodemeimeidenverdeerzi': '姨甥孙',
  'wodemeimeidenverdenver': '姨甥孙女'

  }

  export default name;